# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'ZGNetworking' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ZGNetworking
  pod 'Masonry'
	pod 'AFNetworking', '~> 3.0'

  target 'ZGNetworkingTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ZGNetworkingUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
